### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by RobelTekle** [mongkuen/gatsby-plugin-eslint#10]
In Gatsby v2 it seems that the airbnb configuration for eslint throw an exception
 ```
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint/lib/formatters/stylish'
```

Removing `eslint` from dev dependencies fix the error

**Comment by mongkuen** [comment]
Not sure how to reproduce this? I went through the steps in the current readme for the gatsby-starter-default project and the error didn't show up

**Comment by mongkuen** [comment]
A major breaking version has been released to address `eslint-loader`'s deprecation in favor of `eslint-webpack-plugin`, outdated dependencies should also probably go away now
