### ISSUE TITLE
Doesn't work in a project with the name "public"

### ISSUE THREAD

**Issue by fcaldera** [mongkuen/gatsby-plugin-eslint#11]
If you made the unfortunate decision of naming your project `public`, the plugin won't work. It will skip all your files due the default exclude regular expression:

```js
const exclude = pluginOptions.exclude || /(node_modules|.cache|public)/;
```

It can be fixed by overriding the defaults in your project to something like this:

```js
// gatsby-config.js
{
  resolve: 'gatsby-plugin-eslint',
  options: {
    exclude: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, '.cache'),
      path.resolve(__dirname, 'public')
    ]
  }
}
```

A corner case that may be worth documenting.

**Comment by mongkuen** [comment]
Sure
