### ISSUE TITLE
Difference between setting up eslint manually

### ISSUE THREAD

**Issue by artemartemov** [mongkuen/gatsby-plugin-eslint#12]
Hey there,

I am just curious, is there any added benefits to using this gatsby plugin vs setting up eslint manually within your project?

Thanks!

**Comment by mongkuen** [comment]
Nope, you can read the plugin source (it's like 10 lines) and literally copy/paste it into your project if you'd prefer. 

I just published this plugin so I didn't have to keep doing the same thing over and over in different gatsby projects.
