### ISSUE TITLE
Upgrade dependencies - use ESLint 6 

### ISSUE THREAD

**Issue by mobidev111** [mongkuen/gatsby-plugin-eslint#13]

**Comment by mongkuen** [comment]
sure

**Comment by mobidev111** [comment]
thanks. eslint-loader is still outdated: eslint-loader@3.0.2

**Comment by JustFly1984** [comment]
@mongkuen  please update eslint-loader too

**Comment by mongkuen** [comment]
Sure. I bumped the peerdependency version
