### ISSUE TITLE
Run --fix option with ESLint gatsby plugin

### ISSUE THREAD

**Issue by lam-dan** [mongkuen/gatsby-plugin-eslint#14]
Does anyone know how to run ESLint with the --fix option for the gatsby plugin on development mode? Aka: gatsby develop

**Comment by mongkuen** [comment]
like `yarn run eslint myFolder/myFile.js --fix`

**Comment by lam-dan** [comment]
Yeah, I mean running it as part of the 'gatsby develop' mode as a gatsby config plugin. I figured it out. It's actually adding the fix option in the plugins and setting it to true.
