### ISSUE TITLE
eslint-loader deprecated

### ISSUE THREAD

**Issue by jwkellyiii** [mongkuen/gatsby-plugin-eslint#24]
Is this library still alive? Asking as this library relies on eslint-loader ^3.0.2 as a peerDependency, however eslint-loader has been deprecated in favor of eslint-webpack-plugin. Is there a plan to update this library to move to eslint-webpack-plugin?

**Comment by mongkuen** [comment]
Thanks for bringing my attention to this, revived a major version update to address this
