### ISSUE TITLE
The plugin option documents do not match the code

### ISSUE THREAD

**Issue by bryanpizzillo** [mongkuen/gatsby-plugin-eslint#26]
I am using plugin version 3.0.0 with Gatsby 3.0.0. There is either a bug in the docs, or a bug in the code. The [code](https://github.com/mongkuen/gatsby-plugin-eslint/blob/a2a157e88ea372b3162c1846de49abb7d3ece7f6/src/gatsby-node.js#L4) expects the pluginConfig to have an options property, but pluginConfig IS the options property from gatsby-config. (`const options = pluginOptions.options || {};`)

Using the following config keeps the plugin defaults.
```
{
  resolve: 'gatsby-plugin-eslint',
  options: {
    stages: ['develop'],
    extensions: ['js', 'jsx', 'mdx'],
    exclude: ['node_modules', '.cache', 'public'],
   },
}
```

Using the following config actually uses my config
```
{
   resolve: 'gatsby-plugin-eslint',
   options: {
      options: {
         stages: ['develop'],
	extensions: ['js', 'jsx', 'mdx'],
	exclude: ['node_modules', '.cache', 'public'],
     },
   },
},
```

So either to docs are in error, or the code should be changed to `const options = pluginOptions || {};`.  I assume the error is the latter.

**Comment by mongkuen** [comment]
Thanks for opening this! I see where this was a problem and I'm glad you opened a PR!

Unfortunately there are deeper [issues](https://github.com/mongkuen/gatsby-plugin-eslint/issues/25) with using this plugin with V3 regarding `eslint-loader` and `eslint-webpack-plugin` that wasn't limited to just this particular fix to making this plugin work for V3.

Looking at Gatsby's source again, things have fully transitioned to `eslint-webpack-plugin` - so I've rewritten the plugin to be compatible with V3 [with your suggestions in mind](https://github.com/mongkuen/gatsby-plugin-eslint/commit/d5ee2f6fdf78b2e86fa6c3fc26ad219ce27bb1c8#diff-90dfe890b98b133dd87065d44aa6f5099a1e7f777f5432a17a88be6d2da05a3bR1-R36). Thanks again!
