### ISSUE TITLE
failOnError: false does not seem to work

### ISSUE THREAD

**Issue by ukch** [mongkuen/gatsby-plugin-eslint#4]
Here's the contents of my `gatsby-config.js`:
```javascript
module.exports = {
    siteMetadata: ...,
    plugins: [
        {
            resolve: "gatsby-plugin-eslint",
            options: {
                options: {
                    failOnError: false,
                },
            },
        },
        "gatsby-plugin-react-helmet",
    ],
}
```
Still, all it takes for my build to fail is one single eslint error. What I would like is for all errors to be logged to the console, but for the build to succeed unless there is an actual error which prevents the code from compiling.

**Comment by jacekk** [comment]
@ukch Such config should works as you expect:

```json
{
      resolve: 'gatsby-plugin-eslint',
      options: {
        options: {
            emitWarning: true,
            failOnError: false
        }
    }
}
```

With the `emitWarning` flag, changing `failOnError` values does make a difference :)
