### ISSUE TITLE
Peer dependency `gatsby-plugin-eslint`

### ISSUE THREAD

**Issue by acocheo** [mongkuen/gatsby-plugin-eslint#43]
Please update peerDependencies adding `gatsby-plugin-eslint`  [v4](https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md) compatibility.
Otherwise an update will break packages installation

**Comment by mongkuen** [comment]
https://github.com/mongkuen/gatsby-plugin-eslint/commit/19f8b4bfe212dad6bf003f7d8354b84535737fe6
